"""Add inbound shipment and inbound shipment item tables

Revision ID: 08a913e8f102
Revises: 
Create Date: 2026-02-09 11:53:50.252385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08a913e8f102'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('EXPECTED', 'ARRIVED', 'PROCESSING', 'COMPLETED', name='inboundshipmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_shipments_id'), 'inbound_shipments', ['id'], unique=False)
    op.create_table('inbound_shipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbound_shipment_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inbound_shipment_id'], ['inbound_shipments.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_shipment_items_id'), 'inbound_shipment_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inbound_shipment_items_id'), table_name='inbound_shipment_items')
    op.drop_table('inbound_shipment_items')
    op.drop_index(op.f('ix_inbound_shipments_id'), table_name='inbound_shipments')
    op.drop_table('inbound_shipments')
    # ### end Alembic commands ###
