"""add inbound models

Revision ID: 455bb0f4b1f7
Revises: 9f0430dc11f8
Create Date: 2026-02-09 12:37:30.918103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '455bb0f4b1f7'
down_revision: Union[str, Sequence[str], None] = '9f0430dc11f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_shipment_items', sa.Column('quantity_expected', sa.Integer(), nullable=False))
    op.alter_column('inbound_shipment_items', 'quantity_received',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('inbound_shipment_items', 'created_at')
    op.add_column('inbound_shipments', sa.Column('carrier_name', sa.String(), nullable=True))
    op.add_column('inbound_shipments', sa.Column('tracking_number', sa.String(), nullable=True))
    op.add_column('inbound_shipments', sa.Column('expected_arrival_date', sa.DateTime(), nullable=False))
    op.add_column('inbound_shipments', sa.Column('actual_arrival_date', sa.DateTime(), nullable=True))
    op.drop_column('inbound_shipments', 'arrival_date')
    op.drop_column('inbound_shipments', 'updated_at')
    op.execute("UPDATE products SET sku = '' WHERE sku IS NULL")
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products', 'branch_id')
    op.add_column('purchase_order_items', sa.Column('quantity_ordered', sa.Integer(), nullable=False))
    op.add_column('purchase_order_items', sa.Column('quantity_received', sa.Integer(), nullable=False))
    op.drop_column('purchase_order_items', 'unit_price')
    op.drop_column('purchase_order_items', 'quantity')
    op.add_column('purchase_orders', sa.Column('po_number', sa.String(), nullable=False))
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.drop_column('purchase_orders', 'expected_delivery_date')
    op.drop_column('purchase_orders', 'order_date')
    op.add_column('vendors', sa.Column('email', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('phone', sa.String(), nullable=True))
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=True)
    op.create_index(op.f('ix_vendors_email'), 'vendors', ['email'], unique=True)
    op.drop_column('vendors', 'created_at')
    op.drop_column('vendors', 'is_active')
    op.drop_column('vendors', 'phone_number')
    op.drop_column('vendors', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vendors_email'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.drop_column('vendors', 'phone')
    op.drop_column('vendors', 'email')
    op.add_column('purchase_orders', sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('purchase_orders', sa.Column('expected_delivery_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'po_number')
    op.add_column('purchase_order_items', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('purchase_order_items', sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('purchase_order_items', 'quantity_received')
    op.drop_column('purchase_order_items', 'quantity_ordered')
    op.add_column('products', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('inbound_shipments', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('inbound_shipments', sa.Column('arrival_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('inbound_shipments', 'actual_arrival_date')
    op.drop_column('inbound_shipments', 'expected_arrival_date')
    op.drop_column('inbound_shipments', 'tracking_number')
    op.drop_column('inbound_shipments', 'carrier_name')
    op.add_column('inbound_shipment_items', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('inbound_shipment_items', 'quantity_received',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('inbound_shipment_items', 'quantity_expected')
    # ### end Alembic commands ###
