"""Add docks table

Revision ID: f94472d75e16
Revises: 08a913e8f102
Create Date: 2026-02-09 12:05:25.000878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94472d75e16'
down_revision: Union[str, Sequence[str], None] = '08a913e8f102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dock_type', sa.Enum('INBOUND', 'OUTBOUND', name='docktype'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('docks_pkey'))
    )
    op.create_index(op.f('ix_docks_id'), 'docks', ['id'], unique=False)
    op.create_index(op.f('ix_docks_name'), 'docks', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docks_name'), table_name='docks')
    op.drop_index(op.f('ix_docks_id'), table_name='docks')
    op.drop_table('docks')
    # ### end Alembic commands ###
