from pydantic import BaseModel, EmailStr
from typing import Optional, List
from datetime import datetime
from app.core.models import UserProfile, StockLotStatus

# --- Base & Create Schemas ---

class BranchBase(BaseModel):
    name: str
    location: Optional[str] = None

class BranchCreate(BranchBase):
    pass

class ProductBase(BaseModel):
    name: str
    description: Optional[str] = None
    branch_id: int

class ProductCreate(ProductBase):
    pass

class UserBase(BaseModel):
    email: EmailStr

class UserCreate(UserBase):
    password: str
    profile: UserProfile = UserProfile.OPERATOR
    branch_ids: Optional[List[int]] = None

class InboundOrderBase(BaseModel):
    product_id: int
    quantity: int
    branch_id: int

class InboundOrderCreate(InboundOrderBase):
    pass

class StockLotBase(BaseModel):
    product_id: int
    branch_id: int
    inbound_order_id: int
    quantity: int
    status: StockLotStatus

class StockLotCreate(StockLotBase):
    pass

class OutboundOrderBase(BaseModel):
    product_id: int
    quantity: int
    branch_id: int

class OutboundOrderCreate(OutboundOrderBase):
    pass

# --- Update Schemas ---

class BranchUpdate(BaseModel):
    name: Optional[str] = None
    location: Optional[str] = None

class ProductUpdate(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None

class UserUpdate(BaseModel):
    email: Optional[EmailStr] = None
    is_active: Optional[bool] = None
    profile: Optional[UserProfile] = None
    branch_ids: Optional[List[int]] = None

class StockLotUpdate(BaseModel):
    status: StockLotStatus # The primary field to be updated (e.g., PENDING -> AVAILABLE)
    quantity: Optional[int] = None # Optional: if inspection finds a different quantity

# --- Full Schemas (for API responses) ---

class Branch(BranchBase):
    id: int
    class Config: from_attributes = True

# Pre-declare User and Product to handle circular references
class User(UserBase):
    id: int
    is_active: bool
    profile: UserProfile
    branches: List[Branch] = []
    class Config: from_attributes = True

class Product(ProductBase):
    id: int
    branch: Branch

    # New calculated fields for inventory
    quantity_available: int = 0
    quantity_pending: int = 0
    quantity_quarantined: int = 0

    class Config: from_attributes = True

class StockLot(StockLotBase):
    id: int
    created_at: datetime
    inspected_at: Optional[datetime] = None
    created_by_user: User
    product: Product
    branch: Branch

    class Config: from_attributes = True

class InboundOrder(InboundOrderBase):
    id: int
    user_id: int
    branch: Branch
    product: Product # The product that was ordered
    stock_lots: List[StockLot] = [] # The lots generated by this order

    class Config: from_attributes = True

class OutboundOrder(OutboundOrderBase):
    id: int
    user_id: int
    branch: Branch
    product: Product
    user: User

    class Config: from_attributes = True

# --- Password & Token Schemas ---

class PasswordChange(BaseModel):
    new_password: str

class Token(BaseModel):
    access_token: str
    token_type: str

class TokenData(BaseModel):
    email: Optional[str] = None
